# Use container-based infrastructure for quicker build start-up
sudo: false
language: minimal
env:
  # Path to 'hadolint' binary
  HADOLINT: "${HOME}/hadolint"
install:
  # Download hadolint binary and set it as executable
  - curl -sL -o ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-$(uname -s)-$(uname -m)"
  - chmod 700 ${HADOLINT}
script:
  - ${HADOLINT} --ignore DL3003 --ignore DL3008 Dockerfile
  - docker build . -t varnav/lnd-node
  - docker run --rm -d --name lnd varnav/lnd-node
  - sleep 5
  - docker logs lnd | head -n 20
  - sleep 15
  - docker logs --tail 20 lnd
  - docker stop lnd
